# Generated by Django 2.2.3 on 2019-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='industry_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
