# Generated by Django 2.2.3 on 2019-07-24 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_search_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='last_update',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
