# Generated by Django 2.2.3 on 2019-07-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_search_industry_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upjong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=20)),
                ('industry_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Search')),
            ],
        ),
    ]
