# Generated by Django 2.2.3 on 2019-07-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_upjong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upjong',
            old_name='industry_name',
            new_name='industry_nm',
        ),
    ]
