# Generated by Django 2.2.3 on 2019-07-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190722_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upjong',
            old_name='industry_code',
            new_name='industry_cd',
        ),
        migrations.RenameField(
            model_name='upjong',
            old_name='industry_nm',
            new_name='industry_name',
        ),
    ]
